### ISSUE TITLE
python ./run_taylornet.py searches for file gamma_000.npy

### ISSUE THREAD

**Issue by rupang818** [chaitanya100100/TailorNet#22]
Hi, I'm just trying to see if I can run this in my enviornment, and I'm getting an error because it's looking for a `gamma_000.npy` file. Where can I find this file and/or how do I fix this error?

Thanks in advance!
```
Unable to load font: GLUT_STROKE_ROMAN
Unable to load font: GLUT_STROKE_MONO_ROMAN
Unable to load font: GLUT_BITMAP_9_BY_15
Unable to load font: GLUT_BITMAP_8_BY_13
Unable to load font: GLUT_BITMAP_TIMES_ROMAN_10
Unable to load font: GLUT_BITMAP_TIMES_ROMAN_24
Unable to load font: GLUT_BITMAP_HELVETICA_10
Unable to load font: GLUT_BITMAP_HELVETICA_12
Unable to load font: GLUT_BITMAP_HELVETICA_18
Traceback (most recent call last):
  File "./run_tailornet.py", line 138, in <module>
    run_tailornet()
  File "./run_tailornet.py", line 79, in run_tailornet
    thetas, betas, gammas = get_single_frame_inputs(garment_class, gender)
  File "./run_tailornet.py", line 42, in get_single_frame_inputs
    get_style('000', garment_class=garment_class, gender=gender),
  File "/Users/jihoonkim/Desktop/UCLA/capstone/TailorNet/dataset/canonical_pose_dataset.py", line 11, in get_style
    gammas = np.load(os.path.join(
  File "/Users/jihoonkim/opt/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jihoonkim/Desktop/UCLA/capstone/TailorNet_dataset/t-shirt_male/style/gamma_000.npy'
```

**Comment by chaitanya100100** [comment]
It seems like dataset error. If `TailorNet_dataset/t-shirt_male/style/gamma_000.npy` is not present in the downloaded dataset, you should raise error in the dataset repository: [https://github.com/zycliao/TailorNet_dataset](https://github.com/zycliao/TailorNet_dataset)

**Comment by chaitanya100100** [comment]
@rupang818 , can you tell us the contents of `TailorNet_dataset/t-shirt_male/style` directory?
Adding @zycliao to the thread.

**Comment by chaitanya100100** [comment]
Closing because of inactivity.

**Comment by zahrahosseini99** [comment]
I have the same problem!
