### ISSUE TITLE
NotImplementedError: Platform does not define a GLUT font retrieval function

### ISSUE THREAD

**Issue by fyviezhao** [chaitanya100100/TailorNet#49]
Hi, I run into this error when executing `python run_tailornet.py` on a remote linux machine:
```
Traceback (most recent call last):
  File "run_tailornet.py", line 6, in <module>
    from psbody.mesh import Mesh
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/psbody/mesh/__init__.py", line 10, in <module>
    from .meshviewer import MeshViewer, MeshViewers
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/psbody/mesh/meshviewer.py", line 49, in <module>
    from OpenGL import GL, GLU, GLUT
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
    from OpenGL.GLUT.fonts import *
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
    p = platform.getGLUTFontPointer( name )
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 344, in getGLUTFontPointer
    raise NotImplementedError(
NotImplementedError: Platform does not define a GLUT font retrieval function
```
Can someone help me with this issue? Thanks!

**Comment by fyviezhao** [comment]
This can be fixed by `sudo apt-get install libosmesa6` plus `export PYOPENGL_PLATFORM=osmesa`. Closed.
